# Utilisez une image de base appropriée pour votre application de test
FROM node:alpine

# Définissez le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copiez les fichiers package.json et package-lock.json
COPY package.json .
COPY package-lock.json .

# Installez les dépendances de test
RUN npm ci --only=production

# Copiez le reste des fichiers de l'application
COPY . .

# Exécutez les tests
CMD ["npm", "run", "test"]
